### ISSUE TITLE
Cannot save certificate

### ISSUE THREAD

**Issue by yuri-hattori** [nginx-proxy/docker-letsencrypt-nginx-proxy-companion#642]
Hi, there.

I tried to have nginx automatically renew the certificate using `jrcs / letsencrypt-nginx-proxy-companion` , but failed.

`docker-compose.yml` is described as follows.

docker-compose.yml
```
version: "2"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    container_name: nginx-proxy
    privileged: true
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./log:/var/log/nginx
      - ./my_proxy.conf:/etc/nginx/conf.d/my_proxy.conf
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
    restart: always
    networks:
      - ssl_proxy

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx
    privileged: true
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy
    restart: always
    networks:
      - ssl_proxy

networks:
  ssl_proxy:
    external: true
```

When started with `docker-comonent up`, the following error appeared.
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/simp_le.py", line 1601, in main
    return main_with_exceptions(cli_args)
  File "/usr/lib/python3.8/site-packages/simp_le.py", line 1585, in main_with_exceptions
    persist_new_data(args, existing_data)
  File "/usr/lib/python3.8/site-packages/simp_le.py", line 1443, in persist_new_data
    client = registered_client(
  File "/usr/lib/python3.8/site-packages/simp_le.py", line 1377, in registered_client
    directory = messages.Directory.from_json(net.get(args.server).json())
  File "/usr/lib/python3.8/site-packages/acme/client.py", line 1141, in get
    self._send_request('GET', url, **kwargs), content_type=content_type)
  File "/usr/lib/python3.8/site-packages/acme/client.py", line 1091, in _send_request
    response = self.session.request(method, url, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd49d601070>: Failed to establish a new connection: [Errno -3] Try again'))

Unhandled error has happened, traceback is above

Debugging tips: -v improves output verbosity. Help is available under --help.
```

The latest version of letsencrypt-nginx-proxy-companion image is used.

Can anyone help me to renew my certificate automatically?

**Comment by buchdag** [comment]
Hi.

It looks like your container can't reach `https://acme-v02.api.letsencrypt.org`

Let's say your Let's Encrypt companion container is running and its name is le-companion. The following command will execute curl from "within" the container:

`docker exec le-companion curl -v https://acme-v02.api.letsencrypt.org/directory`

Could you try and report the result ?

**Comment by yuri-hattori** [comment]
Thank you for reply.
The result of running curl inside the container.

```
$ sudo docker exec letsencrypt-nginx curl -v https://acme-v02.api.letsencrypt.org/directory
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0*   Trying 172.65.32.248:443...
* TCP_NODELAY set
* Connected to acme-v02.api.letsencrypt.org (172.65.32.248) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [102 bytes data]
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [2938 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [333 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [70 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=acme-v01.api.letsencrypt.org
*  start date: Apr  7 02:20:06 2020 GMT
*  expire date: Jul  6 02:20:06 2020 GMT
*  subjectAltName: host "acme-v02.api.letsencrypt.org" matched cert's "acme-v02.api.letsencrypt.org"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
} [5 bytes data]
* Using Stream ID: 1 (easy handle 0x55f00aaa01c0)
} [5 bytes data]
> GET /directory HTTP/2
> Host: acme-v02.api.letsencrypt.org
> user-agent: curl/7.67.0
> accept: */*
>
{ [5 bytes data]
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
} [5 bytes data]
< HTTP/2 200
< server: nginx
< date: Tue, 07 Apr 2020 03:36:53 GMT
< content-type: application/json
< content-length: 658
< cache-control: public, max-age=0, no-cache
< x-frame-options: DENY
< strict-transport-security: max-age=604800
<
{ [658 bytes data]
100   658  100   658    0     0    196      0  0:00:03  0:00:03 --:--:--   196
* Connection #0 to host acme-v02.api.letsencrypt.org left intact
{
  "iXBY6tjWjR4": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
  ```

**Comment by buchdag** [comment]
@yuri-hattori are you still experiencing this issue ?

**Comment by buchdag** [comment]
Inactive issue, closing.
