### ISSUE TITLE
Defaults to self sign certificate

### ISSUE THREAD

**Issue by 99Percent** [nginx-proxy/docker-letsencrypt-nginx-proxy-companion#660]
I can't find why it cannot get a certificate. Running LXC under Proxmox with Debian Buster for BTCPayServer. Domain is pay.vmo.mx at Namecheap
Log shows this error:
```
2020/05/24 04:17:24 Received event die for container 1f66f05fb7c2
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 334, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f1c78138a90>: Failed to establish a new connection: [Errno -3] Try again
```
I tried running certbot with all containers stopped and it can get the ssl certificate without any problems.

**Comment by 99Percent** [comment]
Ok, I finally figured out that DNS was not working correctly inside the docker containers.
I had to add the following to /etc/docker/daemon.json:
```json
{
    "dns": ["10.0.0.2", "8.8.8.8"]
}
```
where 10.0.0.2 was changed to the DNS listed in /etc/resolv.conf
I think it is a quirk as to how Proxmox sets up DNS in LXC containers that somehow confuses de docker daemon.
